apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vys91sj38-python 
  janus-idp.io/tekton: vys91sj38-python
  backstage.io/kubernetes-id: vys91sj38-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vys91sj38-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  