apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vys91sj38-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vys91sj38-python 
  name: vys91sj38-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vys91sj38-python 
